ARG FEDORA_VERSION=40
FROM registry.fedoraproject.org/fedora:${FEDORA_VERSION}

ARG USERNAME=dev
ARG UID=1000
ARG GID=1000

WORKDIR /tmp

# Install required packages
RUN dnf reinstall -y shadow-utils \
    && dnf install -y sudo koji git podman fuse-overlayfs --exclude container-selinux \
    && dnf clean all \
    && groupadd -g ${GID} ${USERNAME} \
    && useradd -m -u ${UID} -g ${GID} ${USERNAME} \
    && usermod -aG wheel ${USERNAME} \
    && echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && mkdir -p /workspaces

RUN useradd ${USERNAME}; \
echo ${USERNAME}:10000:5000 > /etc/subuid; \
echo ${USERNAME}:10000:5000 > /etc/subgid;

VOLUME /var/lib/containers
VOLUME /home/${USERNAME}/.local/share/containers

ADD https://github.com/containers/image_build/raw/refs/heads/main/podman/containers.conf /etc/containers/containers.conf
ADD https://github.com/containers/image_build/raw/refs/heads/main/podman/podman-containers.conf /home/podman/.config/containers/containers.conf

RUN chown ${USERNAME}:${USERNAME} -R /home/${USERNAME}

# chmod containers.conf and adjust storage.conf to enable Fuse storage.
RUN chmod 644 /etc/containers/containers.conf
RUN sed -e 's|^#mount_program|mount_program|g' \
           -e '/additionalimage.*/a "/var/lib/shared",' \
           -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
           /usr/share/containers/storage.conf \
           > /etc/containers/storage.conf
# sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock

USER $USERNAME
WORKDIR /workspaces

ENV _CONTAINERS_USERNS_CONFIGURED=""